### PR TITLE
Terminando parte 3. Config Inicial del Proyecto punto 6

### PR DESCRIPTION
**Pull request by JorgeVQA**

### CODE REVIEW

**Comment by JorgeVQA** [comment]
The text in COMMIT does not corresponds with this PR title.   The correct one in this PR's title.   Please omit the one in the COMMIT.

**Comment by JuanDelahozMiranda** [comment]
I don't know what happened, I can't approve this PR :)

**Comment by manuelq12** [comment]
Try now sir @JuanDelahozMiranda

**Review by JuanDelahozMiranda — APPROVED** [review]
So, the structure is Ok, only was set up the files and some examples. now the PR hasn't a title XD
but, this would add later.

**Comment by JorgeVQA** [comment]
Finished Part 3 of this Cypress Workshop.

**Pull request merged**
